name: Check for bugs with PHPStan static analysis tool

on:
    workflow_call:
        inputs:
            php-version:
                description: PHP Version to use
                default: 8.3
                required: false
                type: string

            vendor-bin:
                description: Directory containing PHPStan
                default: ./vendor-bin/phpstan
                required: false
                type: string

jobs:
    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v6

            -   name: Install PHP with extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ inputs.php-version }}
                    coverage: none

            -   name: Install dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            -   name: Install PHPStan
                working-directory: ${{ inputs.vendor-bin }}
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            -   name: Run PHPStan
                run: ${{ inputs.vendor-bin }}/vendor/bin/phpstan analyse --configuration phpstan.neon --memory-limit 2G --no-progress
