name: Run PHPUnit tests

on:
    workflow_call:
        inputs:
            php:
                description: PHP Version to use
                default: 8.3
                required: false
                type: string

            ini-values:
                description: PHP ini values
                required: false
                default: ''
                type: string

            extensions:
                description: PHP extensions to install
                required: false
                default: ''
                type: string

            test-suite:
                description: Test suite to run
                required: true
                type: string

            install-assets:
                description: Build and compile assets
                required: false
                default: false
                type: boolean

jobs:
    phpunit:
        name: Run PHPUnit tests
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v6

            -   name: Install PHP with extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ inputs.php }}
                    ini-values: ${{ inputs.ini-values }}
                    extensions: ${{ inputs.extensions }}
                    coverage: xdebug

            -   name: Install dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            -   name: Build and compile assets
                if: ${{ true == inputs.install-assets }}
                run: |
                    php bin/console importmap:install
                    php bin/console asset-map:compile

            -   name: Run PHPUnit
                run: vendor/bin/phpunit --display-skipped --no-progress --coverage-clover ./clover.xml --testsuite '${{ inputs.test-suite }}'

            -   name: Upload coverage to Codecov
                uses: codecov/codecov-action@v6
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    slug: '${{ github.repository }}'
                    disable_search: true
                    files: ./clover.xml
