name: Run PHPUnit tests

on:
    workflow_call:
        inputs:
            php:
                description: PHP Version to use
                default: 8.3
                required: false
                type: string

            php-ini:
                description: PHP ini values
                required: false
                default: ''
                type: string

            php-extensions:
                description: PHP extensions to install
                required: false
                default: ''
                type: string

            codecov-slug:
                description: The slug used to upload coverage to Codecov
                required: true
                type: string

jobs:
    phpunit:
        name: Run PHPUnit tests
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v6

            -   name: Install PHP with extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ inputs.php }}
                    ini-values: ${{ inputs.php-ini }}
                    extensions: ${{ inputs.php-extensions }}
                    coverage: xdebug

            -   name: Install dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            -   name: Run PHPUnit
                run: vendor/bin/phpunit --display-skipped --no-progress --testsuite test-full --coverage-clover ./clover.xml

            -   name: Upload coverage to Codecov
                uses: codecov/codecov-action@v6
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    slug: '${{ inputs.codecov-slug }}'
                    disable_search: true
                    files: ./clover.xml
