name: Check for upgrade with Rector static analysis tool

on:
    workflow_call:
        inputs:
            php:
                description: PHP Version to use
                default: 8.3
                required: false
                type: string

            vendor-bin:
                description: Directory containing Rector
                default: ./vendor-bin/rector
                required: false
                type: string

jobs:
    rector:
        name: Rector
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v6

            -   name: Install PHP with extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ inputs.php }}
                    coverage: none

            -   name: Install dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            -   name: Install Rector
                working-directory: ${{ inputs.vendor-bin }}
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            -   name: Run Rector
                run: ${{ inputs.vendor-bin }}/vendor/bin/rector process --dry-run --no-progress-bar
