name: Validate Yaml

on:
    workflow_call:
        inputs:
            php-version:
                description: PHP Version to use
                default: 8.3
                required: false
                type: string
            path:
                description: Path to Yaml files
                default: '.github/workflows config translations'
                required: false
                type: string

jobs:
    validate-yaml:
        name: Validate Yaml
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v6

            -   name: Install PHP with extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ inputs.php-version }}
                    coverage: none

            -   name: Install dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            -   name: Validate
                run: php bin/console lint:yaml ${{ inputs.path }} --parse-tags
