name: Validate Markdown

on:
    workflow_call:
        inputs:
            globs:
                description: The globs to check
                default: '**/*.md'
                required: false
                type: string

jobs:
    validate-markdown:
        name: Validate Markdown
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v6

            -   name: Validate
                uses: DavidAnson/markdownlint-cli2-action@v23
                with:
                    globs: ${{ inputs.globs }}
