name: Twig Validate

on:
    workflow_call:
        inputs:
            php:
                description: PHP Version to use
                default: 8.3
                required: false
                type: string
            path:
                description: Path to Twig files
                default: templates
                required: false
                type: string

jobs:
    lint-twig:
        name: Twig Validate
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v6

            -   name: Install PHP with extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ inputs.php }}
                    coverage: none

            -   name: Install dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            -   name: Validate Twig templates
                run: php bin/console lint:twig ${{ inputs.path }} --show-deprecations
